name: Deploy

on:
  push:
    branches:
      - main
      - master
jobs:
    cd:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Deploy Using ssh
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: 22
                script: |
                    cd B3-Financial-Market 
                    git reset --hard HEAD
                    git pull 
                    sudo docker-compose down
                    sudo docker rm -vf $(sudo docker ps -q)
                    sudo docker rmi -f $(sudo docker images -aq) 
                    sudo docker-compose up --detach